### ISSUE TITLE
Add roadmap to documentation webpage

### ISSUE THREAD

**Issue by nicklasfrahm** [mykilio/docs#10]
To show the vision of this ecosystem, a roadmap should be visible in the documentation.

- [ ] Each roadmap item is linked against an issue in the documentation repository
- [ ] Roadmap items are prioritized, but kept as abstract as possible
- [ ] Roadmap allows crazy ideas
